joy_node:
  ros__parameters:
    device_id: 0
    deadzone: 0.05
    autorepeate_rate: 20.0
    
teleop_node:
  ros__parameters:
    axis_linear:
      x: 1
      y: 0
    scale_linear:
      x: 1.7
      y: 1.7
    scale_linear_turbo:
      y: 1.7 

    axis_angular:
      yaw: 3
    scale_angular:
      yaw: 2.0
    scale_angular_turbo:
      yaw: 1.0    



    enable_button: 4
    enable_turbo_buttton: 5
    require_enable_buttton: true    